---
abstract: 'Copy file/directory using rsync, with undo support'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  File::Which: 0
  File::chdir: 0
  Test::More: 0.98
  Test::Perinci::Tx::Manager: 0.41
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Copy-Undoable
requires:
  Builtin::Logged: 0
  File::Trash::Undoable: 0.08
  Log::Any: 0
  Rinci: v1.1.29
  SHARYANTO::File::Util: 0.27
  SHARYANTO::Proc::ChildError: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/File-Copy-Undoable
  repository: http://github.com/sharyanto/perl-File-Copy-Undoable
version: 0.04
